### PR TITLE
Add game speed scaling to instant yields

### PR DESCRIPTION
**Pull request by theazuresoul**
Game speed scaling for instant yields from Ranch, Madrasah, Tophet and Examination Hall

### CODE REVIEW

**Comment by adaneslavo** [comment]
You need to add also math.floor(yield +0.5) to have integers not numbers like 15.66666

**Comment by adaneslavo** [comment]
If define local value you dont need to declare it immediately. So you can add ```local iGameSpeedModifier``` instead of ```local iGameSpeedModifier = 1```.

**Comment by adaneslavo** [comment]
You can add also popups messages for instant yields btw. Copy all stuff from Kleht f.i.

**Comment by adaneslavo** [comment]
Add scaling to Hippodrome too. First ability doesn't have one.

**Comment by theazuresoul** [comment]
I don't think either of those first things are strictly necessary, but I pushed commits for them. The notification issue I'll handle in a separate commit.

**Pull request merged**
